export const WS_EVENTS = {
  // incoming

  NEW_MESSAGE: "NEW_MESSAGE",

  MESSAGE_READ: "MESSAGE_READ",

  NOTIFICATION: "NOTIFICATION",

  CONVERSATION_UPDATED: "CONVERSATION_UPDATED",

  PRESENCE: "PRESENCE",

  HEARTBEAT_ACK: "HEARTBEAT_ACK",

  SUBSCRIBED: "SUBSCRIBED",

  UNSUBSCRIBED: "UNSUBSCRIBED",

  ERROR: "ERROR",

  // outgoing

  HEARTBEAT: "HEARTBEAT",

  SUBSCRIBE_CONVERSATION:
    "SUBSCRIBE_CONVERSATION",

  UNSUBSCRIBE_CONVERSATION:
    "UNSUBSCRIBE_CONVERSATION",
};